//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOVIE()
        {
            this.SHOWs = new HashSet<SHOW>();
        }
    
        public int MovieID { get; set; }
        public string MovieName { get; set; }
        public string PosterURL { get; set; }
        public string Synopsis { get; set; }
        public string TrailerURL { get; set; }
        public int CastingID { get; set; }
        public int DirectorID { get; set; }
        public int GenreID { get; set; }
    
        public virtual CASTING CASTING { get; set; }
        public virtual DIRECTOR DIRECTOR { get; set; }
        public virtual GENRE GENRE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SHOW> SHOWs { get; set; }
    }
}
