//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOVIEHALLSEAT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MOVIEHALLSEAT()
        {
            this.TICKETRESERVATIONs = new HashSet<TICKETRESERVATION>();
        }
    
        public int MovieHallSeatID { get; set; }
        public string SeatNumber { get; set; }
        public int MovieHallID { get; set; }
    
        public virtual MOVIEHALL MOVIEHALL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TICKETRESERVATION> TICKETRESERVATIONs { get; set; }
    }
}
