//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BMSDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TICKETRESERVATION
    {
        public int MovieTicketID { get; set; }
        public int BookingID { get; set; }
        public int MovieHallSeatID { get; set; }
    
        public virtual BOOKING BOOKING { get; set; }
        public virtual MOVIEHALLSEAT MOVIEHALLSEAT { get; set; }
    }
}
